QT += core
QT -= gui

DEFINES += TEST

CONFIG += c++11
#CONFIG += console
CONFIG -= app_bundle

#TARGET = Tests
TEMPLATE = app

INCLUDEPATH += ..

SOURCES += \
    cardreader/inpas/InpasPacketLayer.cpp \
    cardreader/inpas/test/InpasPacketLayerTest.cpp \
    cardreader/sberbank/SberbankPrinter.cpp \
    cardreader/vendotek/VendotekDeviceLan.cpp \
    cardreader/vendotek/test/TlvTest.cpp \
    code_scanner/unitex1/UnitexScanner.cpp \
    code_scanner/unitex1/test/Unitex1ScannerTest.cpp \
    config/v3/automat/Config3AutomatSettings.cpp \
    config/v3/automat/Config3BarcodeList.cpp \
    config/v3/automat/Config3WareGroupList.cpp \
    config/v3/automat/Config3WareLinkList.cpp \
    config/v5/Money.cpp \
    config/v5/RingList2.cpp \
    config/v5/test/RingList2Test.cpp \
    memory/qt/FileMemory.cpp \
    mqtt/MqttPacketLayer.cpp \
    mqtt/MqttPool.cpp \
    mqtt/test/MqttEncoderTest.cpp \
    mqtt/test/MqttPacketLayerTest.cpp \
    tcpip/TcpIpUtils.cpp \
    utils/test/HexTest.cpp \
    utils/test/StringBuilderTest.cpp \
    utils/StringBuilder.cpp \
    utils/Buffer.cpp \
    logger/qt/LogTargetFile.cpp \
    logger/Logger.cpp \
    logger/LogTargetRam.cpp \
    logger/LogTargetUart.cpp \
    test/Test.cpp \
    dex/test/DexReceiverTest.cpp \
    dex/test/DexServerTest.cpp \
    dex/test/TestAuditParse.cpp \
    dex/test/TestDataGenerator.cpp \
    dex/Audit.cpp \
    dex/AuditParser.cpp \
    dex/AuditProduct.cpp \
    dex/DexCrc.cpp \
    dex/DexReceiver.cpp \
    dex/DexSender.cpp \
    dex/DexServer.cpp \
    utils/test/BufferTest.cpp \
    utils/test/JsonTest.cpp \
    utils/test/NetworkProtocolTest.cpp \
    utils/test/StringParserTest.cpp \
    utils/test/UtilsTest.cpp \
    utils/CodePage.cpp \
    utils/Hex.cpp \
    utils/Json.cpp \
    utils/sha1.cpp \
    utils/StringParser.cpp \
    utils/Utils.cpp \
    uart/TestUart.cpp \
    uart/UartStream.cpp \
    timer/Timer.cpp \
    mdb/master/bill_validator/test/MdbMasterBillValidatorTest.cpp \
    mdb/master/bill_validator/MdbBill.cpp \
    mdb/master/bill_validator/MdbMasterBillValidator.cpp \
    mdb/master/coin_changer/test/MdbCoinTest.cpp \
    mdb/master/coin_changer/test/MdbMasterCoinChangerTest.cpp \
    mdb/master/coin_changer/MdbCoin.cpp \
    mdb/master/coin_changer/MdbMasterCoinChanger.cpp \
    mdb/master/MdbMasterEngine.cpp \
    mdb/master/MdbMasterReceiver.cpp \
    mdb/master/MdbMasterSender.cpp \
    mdb/master/MdbMasterTester.cpp \
    mdb/slave/bill_validator/test/MdbSlaveBillValidatorTest.cpp \
    mdb/slave/bill_validator/MdbSlaveBillValidator.cpp \
    mdb/slave/coin_changer/test/MdbSlaveCoinChangerTest.cpp \
    mdb/slave/coin_changer/MdbSlaveCoinChanger.cpp \
    mdb/slave/test/MdbSlaveReceiverTest.cpp \
    mdb/slave/MdbSlave.cpp \
    mdb/slave/MdbSlaveEngine.cpp \
    mdb/slave/MdbSlavePacketReceiver.cpp \
    mdb/slave/MdbSlaveReceiver.cpp \
    mdb/slave/MdbSlaveSender.cpp \
    mdb/slave/MdbSlaveTester.cpp \
    mdb/MdbBridge.cpp \
    mdb/MdbProtocol.cpp \
    CommonTest.cpp \
    evadts/EvadtsParser.cpp \
    executive/ExeMasterReceiver.cpp \
    executive/ExeSlaveReceiver.cpp \
    executive/ExeSniffer.cpp \
    fiscal_register/atol/test/testAtol.cpp \
    fiscal_register/atol/Atol.cpp \
    fiscal_register/atol/AtolPacketLayer.cpp \
    fiscal_register/atol/AtolTaskLayer.cpp \
    fiscal_register/rp_system_1fa/RpSystem1Fa.cpp \
    fiscal_register/rp_system_1fa/RpSystem1FaPacketLayerCom.cpp \
    fiscal_register/rp_system_1fa/RpSystem1FaPacketLayerTcp.cpp \
    fiscal_register/shtrih-m/ShtrihM.cpp \
    fiscal_register/shtrih-m/ShtrihmReceiver.cpp \
    http/test/HttpClientTest.cpp \
    http/HttpClient.cpp \
    http/HttpDownloader.cpp \
    http/HttpResponseParser.cpp \
    sim900/test/GsmDriverTest.cpp \
    sim900/test/GsmTcpConnectionTest.cpp \
    sim900/command/GsmCommand.cpp \
    sim900/command/GsmCommandParser.cpp \
    sim900/command/GsmCommandQueue.cpp \
    sim900/GsmDriver.cpp \
    sim900/tcp/GsmTcpConnection.cpp \
    memory/MemoryCrc.cpp \
    memory/RamMemory.cpp \
    executive/test/ExeSnifferTest.cpp \
    mdb/master/cashless/test/MdbMasterCashlessTest.cpp \
    mdb/master/cashless/MdbMasterCashless.cpp \
    utils/test/ListTest.cpp \
    evadts/test/EvadtsCrcTest.cpp \
    evadts/EvadtsGenerator.cpp \
    executive/ExeSnifferPacketLayer.cpp \
    utils/test/FifoTest.cpp \
    ecp/EcpServer.cpp \
    ecp/test/EcpClientTest.cpp \
    ecp/test/EcpServerTest.cpp \
    ecp/EcpClient.cpp \
    ecp/EcpServerPacketLayer.cpp \
    ecp/EcpClientPacketLayer.cpp \
    ecp/test/EcpClientPacketLayerTest.cpp \
    sim900/GsmFirmwareUpdater.cpp \
    sim900/test/GsmFirmwareUpdaterTest.cpp \
    dex/test/TestDataParser.cpp \
    timer/test/DateTimeTest.cpp \
    timer/DateTime.cpp \
    ecp/test/EcpServerPacketLayerTest.cpp \
    timer/qt/QRealTime.cpp \
    sim900/test/GsmCommandParserTest.cpp \
    http/test/HttpResponseParserTest.cpp \
    http/HttpTransport.cpp \
    http/test/HttpTransportTest.cpp \
    http/Http.cpp \
    http/test/TestHttp.cpp \
    utils/test/CodePageTest.cpp \
    utils/DecimalPoint.cpp \
    utils/test/DecimalPointTest.cpp \
    http/test/HttpDownloaderTest.cpp \
    fiscal_register/terminal_fa/TerminalFa.cpp \
    fiscal_register/terminal_fa/test/TerminalFaTest.cpp \
    fiscal_register/terminal_fa/test/TerminalFaPacketLayerTest.cpp \
    fiscal_register/terminal_fa/TerminalFaPacketLayer.cpp \
    fiscal_register/terminal_fa/TerminalFaCommandLayer.cpp \
    fiscal_register/terminal_fa/test/TerminalFaCommandLayerTest.cpp \
    fiscal_storage/FiscalStorage.cpp \
    fiscal_storage/test/FiscalStorageTest.cpp \
    ecp/EcpClientCommandLayer.cpp \
    ecp/EcpServerCommandLayer.cpp \
    utils/TestEventObserver.cpp \
    event/Event2.cpp \
    event/EventEngine.cpp \
    event/test/EventTest.cpp \
    event/test/EventEngineTest.cpp \
    timer/test/TimerEngineTest.cpp \
    event/EventEnvelope.cpp \
    fiscal_register/FiscalRegister.cpp \
    executive/test/ExeSnifferPacketLayerTest.cpp \
    timer/TimerEngine.cpp \
    sim900/command/GsmCommandCipStatus.cpp \
    sim900/command/GsmCommandDataAndResult.cpp \
    sim900/command/GsmCommandSend.cpp \
    sim900/command/GsmCommandRecv.cpp \
    sim900/GsmStreamParser.cpp \
    timer/TimeTable.cpp \
    timer/test/TimeTableTest.cpp \
    fiscal_register/atol/AtolCommandLayer.cpp \
    fiscal_register/atol/test/testAtolPacketLayer.cpp \
    http/test/TestTcpIp.cpp \
    fiscal_register/atol/test/testAtolTaskLayer.cpp \
    sim900/GsmCertificate.cpp \
    utils/Allocator.cpp \
    evadts/EvadtsChecker.cpp \
    http/HttpRequestParser.cpp \
    http/test/HttpRequestParserTest.cpp \
    cardreader/inpas/test/InpasCrcTest.cpp \
    cardreader/inpas/InpasProtocol.cpp \
    cardreader/inpas/InpasCommandLayer.cpp \
    cardreader/sberbank/test/SberbankCommandLayerTest.cpp \
    cardreader/sberbank/test/BluetoothCrcTest.cpp \
    cardreader/sberbank/BluetoothCrc.cpp \
    cardreader/sberbank/SberbankPacketLayer.cpp \
    cardreader/sberbank/test/SberbankPacketLayerTest.cpp \
    cardreader/sberbank/SberbankFrameLayer.cpp \
    cardreader/sberbank/test/SberbankFrameLayerTest.cpp \
    cardreader/sberbank/SberbankPacketReceiver.cpp \
    cardreader/sberbank/SberbankPacketSender.cpp \
    cardreader/sberbank/SberbankCommandLayer.cpp \
    mdb/test/MdbCrcTest.cpp \
    mdb/master/bill_validator/test/MdbBillValidatorContextTest.cpp \
    ddcmp/Ddcmp.cpp \
    ddcmp/test/DdcmpTest.cpp \
    ddcmp/DdcmpPacketLayer.cpp \
    ddcmp/DdcmpCommandLayer.cpp \
    ddcmp/test/DdcmpPacketLayerTest.cpp \
    mdb/slave/com_gateway/MdbSlaveComGateway.cpp \
    mdb/slave/com_gateway/test/MdbSlaveComGatewayTest.cpp \
    utils/test/NumberTest.cpp \
    sim900/tcp/GsmTcpDispatcher.cpp \
    sim900/tcp/GsmTcpServer.cpp \
    http/HttpServer.cpp \
    http/test/HttpServerTest.cpp \
    ccicsi/CciCsi.cpp \
    ccicsi/CciCsiPacketLayer.cpp \
    ccicsi/CciCsiProtocol.cpp \
    ccicsi/test/CciCsiPacketLayerTest.cpp \
    ccicsi/CciCsiCommandLayer.cpp \
    ccicsi/test/CciCsiCommandLayerTest.cpp \
    config/test/StatStorageTest.cpp \
    config/StatStorage.cpp \
    config/v1/boot/Config1Boot.cpp \
    config/v2/fiscal/Config2Cert.cpp \
    config/v2/fiscal/Config2Fiscal.cpp \
    config/v2/fiscal/test/Config2CertTest.cpp \
    config/v2/fiscal/test/Config2FiscalTest.cpp \
    config/v1/fiscal/Config1Fiscal.cpp \
    config/v1/fiscal/Config1FiscalConverter.cpp \
    config/ConfigErrorList.cpp \
    config/v4/event/Config4Event.cpp \
    config/v4/event/Config4EventIterator.cpp \
    config/v4/event/Config4EventList.cpp \
    config/v4/event/RingList.cpp \
    config/v3/test/Config3AuditFillerTest.cpp \
    config/v3/test/Config3AuditGeneratorTest.cpp \
    config/v3/test/Config3AuditIniterTest.cpp \
    config/v3/test/Config3AuditParserTest.cpp \
    config/v3/test/Config3ConfigGeneratorTest.cpp \
    config/v3/test/Config3ConfigIniterTest.cpp \
    config/v3/test/Config3ConfigParserTest.cpp \
    config/v3/test/Config3ConverterTest.cpp \
    config/v3/test/Config3Test.cpp \
    config/v3/Config3AuditFiller.cpp \
    config/v3/Config3AuditGenerator.cpp \
    config/v3/Config3AuditIniter.cpp \
    config/v3/Config3AuditParser.cpp \
    config/v3/Config3ConfigGenerator.cpp \
    config/v3/Config3ConfigIniter.cpp \
    config/v3/Config3ConfigParser.cpp \
    config/v3/Config3Modem.cpp \
    config/v3/Config3Repairer.cpp \
    config/v3/automat/Config3Automat.cpp \
    config/v3/automat/Config3Device.cpp \
    config/v3/automat/Config3PriceIndex.cpp \
    config/v3/automat/Config3PriceList.cpp \
    config/v3/automat/Config3Product.cpp \
    config/v3/automat/Config3ProductIndex.cpp \
    config/v3/automat/Config3ProductIterator.cpp \
    config/v3/automat/Config3ProductList.cpp \
    config/v3/event/Config3Event.cpp \
    config/v3/event/Config3EventIterator.cpp \
    config/v3/event/Config3EventList.cpp \
    config/v1/event/Config1EventList.cpp \
    config/v1/automat/Config1Automat.cpp \
    config/v2/event/Config2EventList.cpp \
    config/v2/automat/Config2Automat.cpp \
    config/v1/automat/Config1AutomatConverter.cpp \
    config/v1/event/Config1Event.cpp \
    config/v1/event/Config1EventListConverter.cpp \
    config/v2/automat/Config2AutomatConverter.cpp \
    config/v1/automat/Config1PriceIndex.cpp \
    config/v1/automat/Config1PriceList.cpp \
    config/v1/automat/Config1ProductIndex.cpp \
    config/v1/automat/Config1ProductList.cpp \
    config/v2/event/Config2Event.cpp \
    config/v2/automat/Config2PriceList.cpp \
    config/v2/automat/Config2ProductList.cpp \
    config/v3/automat/test/Config1ToConfig3AutomatTest.cpp \
    config/v3/automat/test/Config2ToConfig3AutomatTest.cpp \
    config/v3/automat/test/Config3DeviceTest.cpp \
    config/v3/automat/test/Config3PriceIndexTest.cpp \
    config/v3/automat/test/Config3ProductIndexTest.cpp \
    config/v3/automat/test/Config3ProductIteratorTest.cpp \
    config/v3/event/test/Config2ToConfig3EventListTest.cpp \
    config/v3/event/test/Config3EventListTest.cpp \
    config/v4/event/test/RingListTest.cpp \
    config/v4/event/test/Config4EventListTest.cpp \
    config/v4/test/Config4Test.cpp \
    config/v4/Config4Modem.cpp \
    config/v4/Config4Repairer.cpp \
    config/v4/automat/Config4Automat.cpp \
    config/v4/automat/test/Config4DeviceTest.cpp \
    config/v4/automat/Config4DeviceList.cpp \
    config/v4/automat/Config4ProductList.cpp \
    config/v4/automat/test/Config4AutomatTest.cpp \
    config/v4/automat/Config4AutomatData.cpp \
    config/v4/automat/Config4PaymentStat.cpp \
    config/v4/automat/Config4ProductListData.cpp \
    config/v4/automat/Config4ProductListStat.cpp \
    config/v4/automat/Config4ProductIterator.cpp \
    config/v4/Config4MeiAuditGenerator.cpp \
    config/v4/test/Config4MeiAuditGeneratorTest.cpp \
    config/v4/Config4AuditGenerator.cpp \
    config/v4/Config4AuditIniter.cpp \
    config/v4/Config4AuditParser.cpp \
    logger/RemoteLogger.cpp \
    cardreader/sberbank/SberbankDeviceLan.cpp \
    mdb/slave/cashless/MdbSlaveCashless3.cpp \
    mdb/slave/cashless/test/MdbSlaveCashless3Test.cpp \
    sim900/test/TestGsmHardware.cpp \
    ccicsi/test/TestCciCsiPacketLayer.cpp \
    cardreader/inpas/InpasDeviceLan.cpp \
    cardreader/inpas/test/InpasCommandLayerTest.cpp \
    mdb/slave/test/MdbSlavePacketReceiverTest.cpp \
    mdb/MdbCoinChangerPollParser.cpp \
    mdb/test/MdbCoinChangerPollParserTest.cpp \
    mqtt/MqttClient.cpp \
    mqtt/test/MqttClientTest.cpp \
    cardreader/vendotek/VendotekCommandLayer.cpp \
    cardreader/vendotek/VendotekPacketLayer.cpp \
    cardreader/vendotek/VendotekProtocol.cpp \
    cardreader/vendotek/test/VendotekCommandLayerTest.cpp \
    cardreader/vendotek/test/VendotekPacketLayerTest.cpp \
    cardreader/vendotek/Tlv.cpp \
    mdb/master/cashless/MdbMasterCashlessInterface.cpp \
    ccicsi/test/CciT3CommandLayerTest.cpp \
    ccicsi/CciT3CommandLayer.cpp \
    mqtt/MqttEncoder.cpp \
    ccicsi/Order.cpp

HEADERS += \
    cardreader/ingenico/IngenicoProtocol.h \
    cardreader/vendotek/VendotekDeviceLan.h \
    config/v3/automat/Config3AutomatSettings.h \
    config/v3/automat/Config3BarcodeList.h \
    config/v5/Money.h \
    config/v5/RingList2.h \
    mqtt/MqttPool.h \
    utils/include/StringBuilder.h \
    utils/include/Buffer.h \
    utils/include/List.h \
    logger/include/Logger.h \
    logger/include/LogTargetRam.h \
    logger/include/LogTargetStdout.h \
    logger/include/LogTargetUart.h \
    logger/qt/LogTargetFile.h \
    test/include/Test.h \
    dex/include/Audit.h \
    dex/include/AuditParser.h \
    dex/include/AuditProduct.h \
    dex/include/DexDataGenerator.h \
    dex/include/DexDataParser.h \
    dex/include/DexServer.h \
    dex/test/TestAuditParse.h \
    dex/test/TestDataGenerator.h \
    dex/DexCrc.h \
    dex/DexProtocol.h \
    dex/DexReceiver.h \
    dex/DexSender.h \
    utils/include/CodePage.h \
    utils/include/Event.h \
    utils/include/FastAverage.h \
    utils/include/Fifo.h \
    utils/include/Hex.h \
    utils/include/Json.h \
    utils/include/NetworkProtocol.h \
    utils/include/Number.h \
    utils/include/Queue.h \
    utils/include/sha1.h \
    utils/include/StringFinder.h \
    utils/include/StringParser.h \
    utils/include/TimeHelper.h \
    utils/include/Utils.h \
    utils/include/Version.h \
    uart/include/interface.h \
    uart/include/TestUart.h \
    uart/include/UartStream.h \
    timer/include/Timer.h \
    mdb/master/bill_validator/MdbBill.h \
    mdb/master/bill_validator/MdbMasterBillValidator.h \
    mdb/master/coin_changer/MdbCoin.h \
    mdb/master/coin_changer/MdbMasterCoinChanger.h \
    mdb/master/include/MdbMasterEngine.h \
    mdb/master/MdbMaster.h \
    mdb/master/MdbMasterReceiver.h \
    mdb/master/MdbMasterSender.h \
    mdb/master/MdbMasterTester.h \
    mdb/slave/bill_validator/MdbSlaveBillValidator.h \
    mdb/slave/coin_changer/MdbSlaveCoinChanger.h \
    mdb/slave/include/MdbSlaveEngine.h \
    mdb/slave/MdbSlave.h \
    mdb/slave/MdbSlavePacketReceiver.h \
    mdb/slave/MdbSlaveReceiver.h \
    mdb/slave/MdbSlaveSender.h \
    mdb/slave/MdbSlaveTester.h \
    mdb/MdbBridge.h \
    mdb/MdbProtocol.h \
    mdb/MdbProtocolBillValidator.h \
    mdb/MdbProtocolCashless.h \
    mdb/MdbProtocolCoinChanger.h \
    evadts/EvadtsParser.h \
    evadts/EvadtsProtocol.h \
    executive/include/ExeSniffer.h \
    executive/ExeMasterReceiver.h \
    executive/ExeProtocol.h \
    executive/ExeSlaveReceiver.h \
    fiscal_register/atol/include/Atol.h \
    fiscal_register/atol/AtolPacketLayer.h \
    fiscal_register/atol/AtolProtocol.h \
    fiscal_register/atol/AtolTaskLayer.h \
    fiscal_register/include/FiscalRegister.h \
    fiscal_register/rp_system_1fa/include/RpSystem1Fa.h \
    fiscal_register/rp_system_1fa/RpSystem1FaPacketLayer.h \
    fiscal_register/rp_system_1fa/RpSystem1FaPacketLayerCom.h \
    fiscal_register/rp_system_1fa/RpSystem1FaPacketLayerTcp.h \
    fiscal_register/rp_system_1fa/RpSystem1FaProtocol.h \
    fiscal_register/shtrih-m/include/ShtrihM.h \
    fiscal_register/shtrih-m/ShtrihmProtocol.h \
    fiscal_register/shtrih-m/ShtrihmReceiver.h \
    http/include/HttpClient.h \
    http/include/HttpDownloader.h \
    http/HttpResponseParser.h \
    sim900/include/GsmDriver.h \
    sim900/include/GsmTcpConnection.h \
    sim900/command/GsmCommand.h \
    sim900/command/GsmCommandParser.h \
    sim900/command/GsmCommandQueue.h \
    sim900/GsmHardware.h \
    memory/include/Memory.h \
    memory/include/MemoryCrc.h \
    memory/include/RamMemory.h \
    mdb/master/cashless/MdbMasterCashless.h \
    evadts/EvadtsGenerator.h \
    executive/ExeSnifferPacketLayer.h \
    evadts/EvadtsParserAdapter.h \
    ecp/EcpProtocol.h \
    ecp/include/EcpClient.h \
    ecp/include/EcpServer.h \
    ecp/EcpServerPacketLayer.h \
    ecp/EcpClientPacketLayer.h \
    sim900/GsmFirmwareUpdater.h \
    dex/test/TestDataParser.h \
    timer/include/TestRealTime.h \
    timer/include/RealTime.h \
    timer/include/DateTime.h \
    timer/qt/QRealTime.h \
    http/include/HttpTransport.h \
    http/include/Http.h \
    utils/include/DecimalPoint.h \
    fiscal_register/terminal_fa/TerminalFaProtocol.h \
    fiscal_register/terminal_fa/include/TerminalFa.h \
    fiscal_register/terminal_fa/TerminalFaPacketLayer.h \
    fiscal_register/terminal_fa/TerminalFaCommandLayer.h \
    fiscal_storage/include/FiscalStorage.h \
    ecp/EcpClientCommandLayer.h \
    ecp/EcpServerCommandLayer.h \
    utils/include/TestEventObserver.h \
    event/include/Event2.h \
    event/include/EventEngine.h \
    event/include/TestEventEngine.h \
    event/include/EventEnvelope.h \
    timer/include/TimerEngine.h \
    sim900/command/GsmCommandDataAndResult.h \
    sim900/command/GsmCommandSend.h \
    sim900/command/GsmCommandCipStatus.h \
    sim900/command/GsmCommandRecv.h \
    sim900/GsmStreamParser.h \
    platform/x64/include/platform.h \
    timer/include/TimeTable.h \
    fiscal_register/atol/AtolCommandLayer.h \
    http/test/TestTcpIp.h \
    utils/include/Allocator.h \
    evadts/EvadtsChecker.h \
    http/HttpRequestParser.h \
    cardreader/inpas/InpasProtocol.h \
    cardreader/inpas/InpasCommandLayer.h \
    cardreader/sberbank/BluetoothCrc.h \
    cardreader/sberbank/SberbankPacketLayer.h \
    cardreader/sberbank/SberbankProtocol.h \
    cardreader/sberbank/SberbankFrameLayer.h \
    cardreader/sberbank/SberbankCommandLayer.h \
    mdb/master/cashless/test/TestCashlessEventEngine.h \
    ddcmp/Ddcmp.h \
    ddcmp/DdcmpProtocol.h \
    ddcmp/DdcmpPacketLayer.h \
    ddcmp/DdcmpCommandLayer.h \
    mdb/slave/com_gateway/MdbSlaveComGateway.h \
    mdb/MdbProtocolComGateway.h \
    ccicsi/CciCsiPacketLayer.h \
    ccicsi/CciCsiProtocol.h \
    config/v1/boot/Config1Boot.h \
    config/v2/fiscal/Config2Cert.h \
    config/v2/fiscal/Config2Fiscal.h \
    config/v1/fiscal/Config1Fiscal.h \
    config/v1/fiscal/Config1FiscalConverter.h \
    config/v4/event/Config4Event.h \
    config/v4/event/Config4EventData.h \
    config/v4/event/Config4EventIterator.h \
    config/v4/event/Config4EventList.h \
    config/v4/event/RingList.h \
    config/v3/Config3AuditFiller.h \
    config/v3/Config3AuditGenerator.h \
    config/v3/Config3AuditIniter.h \
    config/v3/Config3AuditParser.h \
    config/v3/Config3ConfigGenerator.h \
    config/v3/Config3ConfigIniter.h \
    config/v3/Config3ConfigParser.h \
    config/v3/Config3Modem.h \
    config/v3/Config3Repairer.h \
    config/v3/automat/Config3Automat.h \
    config/v3/automat/Config3AutomatData.h \
    config/v3/automat/Config3Device.h \
    config/v3/automat/Config3PriceIndex.h \
    config/v3/automat/Config3PriceList.h \
    config/v3/automat/Config3Product.h \
    config/v3/automat/Config3ProductIndex.h \
    config/v3/automat/Config3ProductIterator.h \
    config/v3/automat/Config3ProductList.h \
    config/v3/event/Config3Event.h \
    config/v3/event/Config3EventData.h \
    config/v3/event/Config3EventIterator.h \
    config/v3/event/Config3EventList.h \
    config/v1/event/Config1EventList.h \
    config/v1/automat/Config1Automat.h \
    config/v2/event/Config2EventList.h \
    config/v2/automat/Config2Automat.h \
    config/v1/automat/Config1AutomatConverter.h \
    config/v1/event/Config1Event.h \
    config/v1/event/Config1EventListConverter.h \
    config/v2/automat/Config2AutomatConverter.h \
    config/v1/automat/Config1PriceIndex.h \
    config/v1/automat/Config1PriceList.h \
    config/v1/automat/Config1ProductIndex.h \
    config/v1/automat/Config1ProductList.h \
    config/v2/event/Config2Event.h \
    config/v2/automat/Config2PriceList.h \
    config/v2/automat/Config2ProductList.h \
    config/v4/Config4Modem.h \
    config/v4/Config4Repairer.h \
    config/v4/automat/Config4Automat.h \
    config/v4/automat/Config4AutomatData.h \
    config/v4/automat/Config4DeviceList.h \
    config/v4/automat/Config4ProductList.h \
    config/v4/automat/Config4PaymentStat.h \
    config/v4/automat/Config4ProductListData.h \
    config/v4/automat/Config4ProductListStat.h \
    config/v4/automat/Config4ProductIterator.h \
    config/v4/Config4MeiAuditGenerator.h \
    config/v4/Config4AuditGenerator.h \
    config/v4/Config4AuditIniter.h \
    config/v4/Config4AuditParser.h \
    cardreader/sberbank/SberbankDeviceLan.h \
    mdb/slave/cashless/MdbSlaveCashless3.h \
    sim900/test/TestGsmHardware.h \
    ccicsi/test/TestCciCsiPacketLayer.h \
    cardreader/inpas/InpasDeviceLan.h \
    mdb/MdbCoinChangerPollParser.h \
    cardreader/vendotek/VendotekCommandLayer.h \
    cardreader/vendotek/VendotekPacketLayer.h \
    cardreader/vendotek/VendotekProtocol.h \
    cardreader/vendotek/Tlv.h \
    mdb/master/cashless/MdbMasterCashlessInterface.h \
    mqtt/include/MqttClient.h

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
