#ifndef LIB_ORANGEDATA_PROTOCOL_H
#define LIB_ORANGEDATA_PROTOCOL_H

namespace OrangeData {

#define ORANGEDATA_MANUFACTURER	"ORG"
#define ORANGEDATA_MODEL		"Orange Data"
#define ORANGEDATA_ID_SIZE 32
#define ORANGEDATA_REQUEST_SIZE 2000
#define ORANGEDATA_RECV_TIMEOUT 10000
#define ORANGEDATA_POLL_DELAY 2000
#define ORANGEDATA_TRY_MAX 5
#define ORANGEDATA_TRY_DELAY 30000

}

#endif
