QT += core
QT -= gui

DEFINES += TEST

CONFIG += c++11
#CONFIG += console
CONFIG -= app_bundle

#TARGET = Tests
TEMPLATE = app

INCLUDEPATH += common extern/wolfssl

SOURCES += \
    UnitTest.cpp \
    common/config/v3/automat/Config3AutomatSettings.cpp \
    common/logger/Logger.cpp \
    common/logger/LogTargetRam.cpp \
    common/mqtt/MqttPool.cpp \
    common/tcpip/TcpIpUtils.cpp \
    common/test/Test.cpp \
    common/utils/Buffer.cpp \
    common/utils/StringBuilder.cpp \
    common/mdb/master/bill_validator/MdbBill.cpp \
    common/mdb/master/bill_validator/MdbMasterBillValidator.cpp \
    common/mdb/master/cashless/MdbMasterCashless.cpp \
    common/mdb/master/coin_changer/MdbCoin.cpp \
    common/mdb/master/coin_changer/MdbMasterCoinChanger.cpp \
    common/mdb/master/MdbMasterEngine.cpp \
    common/mdb/master/MdbMasterReceiver.cpp \
    common/mdb/master/MdbMasterSender.cpp \
    common/mdb/slave/bill_validator/MdbSlaveBillValidator.cpp \
    common/mdb/slave/coin_changer/MdbSlaveCoinChanger.cpp \
    common/mdb/slave/MdbSlave.cpp \
    common/mdb/slave/MdbSlaveEngine.cpp \
    common/mdb/slave/MdbSlavePacketReceiver.cpp \
    common/mdb/slave/MdbSlaveReceiver.cpp \
    common/mdb/slave/MdbSlaveSender.cpp \
    common/mdb/MdbBridge.cpp \
    common/mdb/MdbProtocol.cpp \
    common/timer/Timer.cpp \
    common/memory/MemoryCrc.cpp \
    common/utils/StringParser.cpp \
    common/memory/RamMemory.cpp \
    common/uart/TestUart.cpp \
    common/utils/Hex.cpp \
    common/timer/DateTime.cpp \
    common/http/Http.cpp \
    common/http/test/TestTcpIp.cpp \
    common/http/test/TestHttp.cpp \
    common/utils/Json.cpp \
    common/utils/CodePage.cpp \
    common/utils/Utils.cpp \
    common/utils/DecimalPoint.cpp \
    common/beeper/Gramophone.cpp \
    common/buttons/Button.cpp \
    common/buttons/ButtonEngine.cpp \
    common/evadts/EvadtsGenerator.cpp \
    common/dex/DexCrc.cpp \
    common/evadts/EvadtsParser.cpp \
    common/mdb/slave/MdbSlaveTester.cpp \
    common/utils/TestEventObserver.cpp \
    common/event/Event2.cpp \
    common/event/EventEnvelope.cpp \
    common/fiscal_register/FiscalRegister.cpp \
    common/timer/TimerEngine.cpp \
    common/timer/TimeTable.cpp \
    common/timer/qt/QRealTime.cpp \
    extern/wolfssl/wolfcrypt/src/tfm.c \
    lib/modem/test/EventRegistrarTest.cpp \
    lib/modem/EventRegistrar.cpp \
    lib/modem/ConfigMaster.cpp \
    lib/modem/ConfigUpdater.cpp \
    lib/sale_manager/exe_master/test/ExeMasterTest.cpp \
    lib/sale_manager/exe_master/test/SaleManagerExeMasterTest.cpp \
    lib/sale_manager/exe_master/ExeMasterPacketLayer.cpp \
    lib/sale_manager/exe_master/SaleManagerExeMasterCore.cpp \
    lib/sale_manager/exe_master/ExeMaster.cpp \
    lib/sale_manager/mdb_master/test/SaleManagerMdbMasterTest.cpp \
    lib/fiscal_register/orange_data/OrangeDataCommandLayer.cpp \
    lib/fiscal_register/orange_data/OrangeDataResponseParser.cpp \
    lib/fiscal_register/orange_data/WolfSslConnection.cpp \
    lib/fiscal_register/orange_data/WolfSslAdapter.cpp \
    lib/fiscal_register/orange_data/test/WolfSslConnectionTest.cpp \
    lib/fiscal_register/orange_data/test/WolfSslRsaSignTest.cpp \
    lib/fiscal_register/orange_data/test/OrangeDataCommandLayerTest.cpp \
    extern/wolfssl/src/internal.c \
    extern/wolfssl/src/keys.c \
    extern/wolfssl/src/ssl.c \
    extern/wolfssl/src/tls.c \
    extern/wolfssl/src/tls13.c \
    extern/wolfssl/src/wolfio.c \
    extern/wolfssl/wolfcrypt/src/port/st/stm32.c \
    extern/wolfssl/wolfcrypt/src/aes.c \
    extern/wolfssl/wolfcrypt/src/arc4.c \
    extern/wolfssl/wolfcrypt/src/asn.c \
    extern/wolfssl/wolfcrypt/src/coding.c \
    extern/wolfssl/wolfcrypt/src/dh.c \
    extern/wolfssl/wolfcrypt/src/error.c \
    extern/wolfssl/wolfcrypt/src/hash.c \
    extern/wolfssl/wolfcrypt/src/hmac.c \
    extern/wolfssl/wolfcrypt/src/integer.c \
    extern/wolfssl/wolfcrypt/src/logging.c \
    extern/wolfssl/wolfcrypt/src/md5.c \
    extern/wolfssl/wolfcrypt/src/memory.c \
    extern/wolfssl/wolfcrypt/src/misc.c \
    extern/wolfssl/wolfcrypt/src/pkcs12.c \
    extern/wolfssl/wolfcrypt/src/pkcs7.c \
    extern/wolfssl/wolfcrypt/src/pwdbased.c \
    extern/wolfssl/wolfcrypt/src/random.c \
    extern/wolfssl/wolfcrypt/src/rsa.c \
    extern/wolfssl/wolfcrypt/src/sha.c \
    extern/wolfssl/wolfcrypt/src/sha256.c \
    extern/wolfssl/wolfcrypt/src/wc_encrypt.c \
    extern/wolfssl/wolfcrypt/src/wc_port.c \
    extern/wolfssl/qt/wolfssl_time.cpp \
    extern/wolfssl/wolfcrypt/src/signature.c \
    common/fiscal_storage/FiscalStorage.cpp \
    extern/wolfssl/wolfcrypt/src/wolfmath.c \
    common/memory/MallocTest.cpp \
    common/http/HttpResponseParser.cpp \
    lib/fiscal_register/chekonline/ChekOnlineResponseParser.cpp \
    lib/fiscal_register/chekonline/test/ChekOnlineResponsePareserTest.cpp \
    lib/modem/test/ConfigUpdaterTest.cpp \
    lib/fiscal_manager/FiscalManager.cpp \
    lib/fiscal_manager/test/FiscalManagerTest.cpp \
    common/event/EventEngine.cpp \
    lib/fiscal_register/orange_data/test/OrangeDataCheckResponsePareserTest.cpp \
    lib/fiscal_register/orange_data/test/OrangeDataPollResponsePareserTest.cpp \
    lib/sale_manager/mdb_slave/EvadtsEventProcessor.cpp \
    lib/sale_manager/mdb_slave/MdbSnifferCashless.cpp \
    lib/sale_manager/mdb_slave/MdbSnifferCoinChanger.cpp \
    lib/sale_manager/mdb_slave/test/MdbSnifferCoinChangerTest.cpp \
    lib/sale_manager/mdb_slave/test/MdbSnifferCashlessTest.cpp \
    lib/sale_manager/mdb_slave/test/SaleManagerMdbSlaveTest.cpp \
    lib/sale_manager/mdb_slave/SaleManagerMdbSlaveCore.cpp \
    lib/sale_manager/mdb_slave/MdbSnifferBillValidator.cpp \
    lib/sale_manager/mdb_slave/test/MdbSnifferBillValidatorTest.cpp \
    lib/fiscal_register/chekonline/test/ChekOnlineCommandLayerTest.cpp \
    lib/fiscal_register/chekonline/ChekOnlineCommandLayer.cpp \
    common/evadts/EvadtsChecker.cpp \
    common/mdb/slave/com_gateway/MdbSlaveComGateway.cpp \
    lib/fiscal_register/nanokassa/NanokassaCommandLayer.cpp \
    lib/fiscal_register/nanokassa/test/NanokassaCommandLayerTest.cpp \
    lib/fiscal_register/nanokassa/NanokassaResponseParser.cpp \
    lib/fiscal_register/ephor/Ephor.cpp \
    lib/fiscal_register/ephor/EphorCommandLayer.cpp \
    lib/fiscal_register/ephor/EphorResponseParser.cpp \
    lib/fiscal_register/ephor/test/EphorCommandLayerTest.cpp \
    common/http/HttpClient.cpp \
    lib/erp/test/ErpCommandProcessorTest.cpp \
    lib/erp/ErpCommandProcessor.cpp \
    lib/erp/ErpCashless.cpp \
    common/http/HttpServer.cpp \
    common/http/HttpRequestParser.cpp \
    common/config/StatStorage.cpp \
    common/config/ConfigErrorList.cpp \
    common/config/v3/Config3Modem.cpp \
    common/config/v4/Config4Modem.cpp \
    common/config/v4/event/Config4Event.cpp \
    common/config/v4/event/Config4EventList.cpp \
    common/config/v4/automat/Config4Automat.cpp \
    common/config/v4/Config4ConfigIniter.cpp \
    common/config/v4/Config4ConfigParser.cpp \
    common/config/v1/boot/Config1Boot.cpp \
    common/config/v2/fiscal/Config2Cert.cpp \
    common/config/v2/fiscal/Config2Fiscal.cpp \
    common/config/v4/Config4AuditGenerator.cpp \
    common/config/v3/automat/Config3PriceIndex.cpp \
    common/config/v3/automat/Config3ProductIndex.cpp \
    common/config/v3/automat/Config3ProductIterator.cpp \
    common/config/v3/automat/Config3PriceList.cpp \
    common/config/v4/event/Config4EventIterator.cpp \
    common/config/v3/automat/Config3Automat.cpp \
    common/config/v3/event/Config3Event.cpp \
    common/config/v3/event/Config3EventIterator.cpp \
    common/config/v3/event/Config3EventList.cpp \
    common/config/v3/automat/Config3Device.cpp \
    common/config/v3/automat/Config3ProductList.cpp \
    common/config/v3/automat/Config3Product.cpp \
    common/config/v3/Config3ConfigIniter.cpp \
    common/config/v3/Config3ConfigParser.cpp \
    common/config/v3/Config3AuditGenerator.cpp \
    common/config/v4/automat/Config4DeviceList.cpp \
    common/config/v4/automat/Config4ProductIterator.cpp \
    common/config/v4/automat/Config4AutomatData.cpp \
    common/config/v4/automat/Config4PaymentStat.cpp \
    common/config/v4/automat/Config4ProductList.cpp \
    common/config/v4/automat/Config4ProductListData.cpp \
    common/config/v4/automat/Config4ProductListStat.cpp \
    common/mdb/master/cashless/TestMdbMasterCashless.cpp \
    common/logger/RemoteLogger.cpp \
    lib/sale_manager/mdb_master/SaleManagerMdbMasterCore.cpp \
    lib/sale_manager/order/MdbSlaveSpire.cpp \
    lib/sale_manager/order/test/MdbSlaveSpireTest.cpp \
    lib/sale_manager/order/test/SaleManagerOrderCoreTest.cpp \
    lib/sale_manager/order/SaleManagerOrderCore.cpp \
    lib/sale_manager/mdb_no_cashless/SaleManagerMdbNoCashlessCore.cpp \
    lib/sale_manager/mdb_no_cashless/test/SaleManagerMdbNoCashlessTest.cpp \
    common/mdb/slave/cashless/MdbSlaveCashless3.cpp \
    lib/sale_manager/cci_franke/test/CsiFrankeCommandLayerTest.cpp \
    lib/sale_manager/cci_franke/CciFrankeCommandLayer.cpp \
    lib/client/ClientContext.cpp \
    common/ccicsi/test/TestCciCsiPacketLayer.cpp \
    common/mdb/master/cashless/MdbMasterCashlessStack.cpp \
    common/mdb/master/cashless/MdbMasterCashlessInterface.cpp \
    common/mqtt/MqttClient.cpp \
    common/mqtt/test/MqttClientTest.cpp \
    common/ccicsi/Order.cpp \
    common/mqtt/MqttEncoder.cpp

HEADERS += \
    config.h \
    common/logger/include/Logger.h \
    common/logger/include/LogTargetRam.h \
    common/logger/include/LogTargetStdout.h \
    common/test/include/Test.h \
    common/utils/include/List.h \
    common/utils/include/StringBuilder.h \
    common/mdb/master/bill_validator/MdbBill.h \
    common/mdb/master/bill_validator/MdbMasterBillValidator.h \
    common/mdb/master/cashless/MdbMasterCashless.h \
    common/mdb/master/coin_changer/MdbCoin.h \
    common/mdb/master/coin_changer/MdbMasterCoinChanger.h \
    common/mdb/master/include/MdbMasterEngine.h \
    common/mdb/master/MdbMaster.h \
    common/mdb/master/MdbMasterReceiver.h \
    common/mdb/master/MdbMasterSender.h \
    common/mdb/slave/bill_validator/MdbSlaveBillValidator.h \
    common/mdb/slave/cashless/MdbSlaveCashless3.h \
    common/mdb/slave/coin_changer/MdbSlaveCoinChanger.h \
    common/mdb/slave/include/MdbSlaveEngine.h \
    common/mdb/slave/MdbSlave.h \
    common/mdb/slave/MdbSlavePacketReceiver.h \
    common/mdb/slave/MdbSlaveReceiver.h \
    common/mdb/slave/MdbSlaveSender.h \
    common/mdb/MdbBridge.h \
    common/mdb/MdbProtocol.h \
    common/mdb/MdbProtocolBillValidator.h \
    common/mdb/MdbProtocolCashless.h \
    common/mdb/MdbProtocolCoinChanger.h \
    common/timer/include/Timer.h \
    common/memory/include/MemoryCrc.h \
    common/utils/include/StringParser.h \
    common/utils/include/Event.h \
    common/fiscal_register/include/FiscalRegister.h \
    common/memory/include/RamMemory.h \
    common/uart/include/TestUart.h \
    common/executive/ExeProtocol.h \
    common/mdb/master/bill_validator/TestMdbMasterBillValidator.h \
    common/mdb/master/cashless/TestMdbMasterCashless.h \
    common/mdb/master/coin_changer/TestMdbMasterCoinChanger.h \
    common/fiscal_register/include/TestFiscalRegister.h \
    common/http/include/Http.h \
    common/http/include/TestHttp.h \
    common/beeper/include/Gramophone.h \
    common/dex/DexCrc.h \
    common/evadts/EvadtsGenerator.h \
    common/evadts/EvadtsParser.h \
    common/utils/include/DecimalPoint.h \
    common/timer/include/TestRealTime.h \
    common/timer/include/DateTime.h \
    common/timer/include/TimerEngine.h \
    common/timer/qt/QRealTime.h \
    common/event/include/Event2.h \
    common/event/include/EventEngine.h \
    common/event/include/EventEnvelope.h \
    common/event/include/TestEventEngine.h \
    common/mdb/slave/MdbSlaveTester.h \
    common/mdb/slave/cashless/TestMdbSlaveCashless.h \
    common/mdb/slave/bill_validator/TestMdbSlaveBillValidator.h \
    common/mdb/slave/coin_changer/TestMdbSlaveCoinChanger.h \
    common/platform/include/platform.h \
    common/platform/x64/include/platform.h \
    lib/erp/ErpAgentCore.h \
    lib/erp/ErpProtocol.h \
    lib/sale_manager/exe_master/ExeMasterPacketLayer.h \
    lib/sale_manager/exe_master/SaleManagerExeMasterCore.h \
    lib/sale_manager/exe_master/ExeMaster.h \
    lib/modem/ModemLed.h \
    lib/modem/ConfigMaster.h \
    lib/modem/ConfigUpdater.h \
    lib/modem/EventRegistrar.h \
    lib/fiscal_register/orange_data/OrangeDataCommandLayer.h \
    lib/fiscal_register/orange_data/OrangeDataResponseParser.h \
    lib/fiscal_register/orange_data/WolfSslConnection.h \
    lib/fiscal_register/orange_data/WolfSslAdapter.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/atmel/atmel.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/caam/caam_driver.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/caam/wolfcaam.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/caam/wolfcaam_sha.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/cavium/cavium_nitrox.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/intel/quickassist.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/intel/quickassist_mem.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/nxp/ksdk_port.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/pic32/pic32mz-crypt.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/st/stm32.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/ti/ti-ccm.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/ti/ti-hash.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/xilinx/xil-sha3.h \
    extern/wolfssl/wolfssl/wolfcrypt/port/nrf51.h \
    extern/wolfssl/wolfssl/wolfcrypt/aes.h \
    extern/wolfssl/wolfssl/wolfcrypt/arc4.h \
    extern/wolfssl/wolfssl/wolfcrypt/asn.h \
    extern/wolfssl/wolfssl/wolfcrypt/asn_public.h \
    extern/wolfssl/wolfssl/wolfcrypt/async.h \
    extern/wolfssl/wolfssl/wolfcrypt/blake2-impl.h \
    extern/wolfssl/wolfssl/wolfcrypt/blake2-int.h \
    extern/wolfssl/wolfssl/wolfcrypt/blake2.h \
    extern/wolfssl/wolfssl/wolfcrypt/camellia.h \
    extern/wolfssl/wolfssl/wolfcrypt/chacha.h \
    extern/wolfssl/wolfssl/wolfcrypt/chacha20_poly1305.h \
    extern/wolfssl/wolfssl/wolfcrypt/cmac.h \
    extern/wolfssl/wolfssl/wolfcrypt/coding.h \
    extern/wolfssl/wolfssl/wolfcrypt/compress.h \
    extern/wolfssl/wolfssl/wolfcrypt/cpuid.h \
    extern/wolfssl/wolfssl/wolfcrypt/cryptodev.h \
    extern/wolfssl/wolfssl/wolfcrypt/curve25519.h \
    extern/wolfssl/wolfssl/wolfcrypt/des3.h \
    extern/wolfssl/wolfssl/wolfcrypt/dh.h \
    extern/wolfssl/wolfssl/wolfcrypt/dsa.h \
    extern/wolfssl/wolfssl/wolfcrypt/ecc.h \
    extern/wolfssl/wolfssl/wolfcrypt/ed25519.h \
    extern/wolfssl/wolfssl/wolfcrypt/error-crypt.h \
    extern/wolfssl/wolfssl/wolfcrypt/fe_operations.h \
    extern/wolfssl/wolfssl/wolfcrypt/fips.h \
    extern/wolfssl/wolfssl/wolfcrypt/fips_test.h \
    extern/wolfssl/wolfssl/wolfcrypt/ge_operations.h \
    extern/wolfssl/wolfssl/wolfcrypt/hash.h \
    extern/wolfssl/wolfssl/wolfcrypt/hc128.h \
    extern/wolfssl/wolfssl/wolfcrypt/hmac.h \
    extern/wolfssl/wolfssl/wolfcrypt/idea.h \
    extern/wolfssl/wolfssl/wolfcrypt/integer.h \
    extern/wolfssl/wolfssl/wolfcrypt/logging.h \
    extern/wolfssl/wolfssl/wolfcrypt/md2.h \
    extern/wolfssl/wolfssl/wolfcrypt/md4.h \
    extern/wolfssl/wolfssl/wolfcrypt/md5.h \
    extern/wolfssl/wolfssl/wolfcrypt/mem_track.h \
    extern/wolfssl/wolfssl/wolfcrypt/memory.h \
    extern/wolfssl/wolfssl/wolfcrypt/misc.h \
    extern/wolfssl/wolfssl/wolfcrypt/mpi_class.h \
    extern/wolfssl/wolfssl/wolfcrypt/mpi_superclass.h \
    extern/wolfssl/wolfssl/wolfcrypt/pkcs12.h \
    extern/wolfssl/wolfssl/wolfcrypt/pkcs7.h \
    extern/wolfssl/wolfssl/wolfcrypt/poly1305.h \
    extern/wolfssl/wolfssl/wolfcrypt/pwdbased.h \
    extern/wolfssl/wolfssl/wolfcrypt/rabbit.h \
    extern/wolfssl/wolfssl/wolfcrypt/random.h \
    extern/wolfssl/wolfssl/wolfcrypt/ripemd.h \
    extern/wolfssl/wolfssl/wolfcrypt/rsa.h \
    extern/wolfssl/wolfssl/wolfcrypt/selftest.h \
    extern/wolfssl/wolfssl/wolfcrypt/settings.h \
    extern/wolfssl/wolfssl/wolfcrypt/sha.h \
    extern/wolfssl/wolfssl/wolfcrypt/sha256.h \
    extern/wolfssl/wolfssl/wolfcrypt/sha3.h \
    extern/wolfssl/wolfssl/wolfcrypt/sha512.h \
    extern/wolfssl/wolfssl/wolfcrypt/signature.h \
    extern/wolfssl/wolfssl/wolfcrypt/sp.h \
    extern/wolfssl/wolfssl/wolfcrypt/sp_int.h \
    extern/wolfssl/wolfssl/wolfcrypt/srp.h \
    extern/wolfssl/wolfssl/wolfcrypt/tfm.h \
    extern/wolfssl/wolfssl/wolfcrypt/types.h \
    extern/wolfssl/wolfssl/wolfcrypt/visibility.h \
    extern/wolfssl/wolfssl/wolfcrypt/wc_encrypt.h \
    extern/wolfssl/wolfssl/wolfcrypt/wc_port.h \
    extern/wolfssl/wolfssl/wolfcrypt/wolfevent.h \
    extern/wolfssl/wolfssl/wolfcrypt/wolfmath.h \
    extern/wolfssl/wolfssl/callbacks.h \
    extern/wolfssl/wolfssl/certs_test.h \
    extern/wolfssl/wolfssl/crl.h \
    extern/wolfssl/wolfssl/error-ssl.h \
    extern/wolfssl/wolfssl/internal.h \
    extern/wolfssl/wolfssl/ocsp.h \
    extern/wolfssl/wolfssl/options.h \
    extern/wolfssl/wolfssl/options.h.in \
    extern/wolfssl/wolfssl/sniffer.h \
    extern/wolfssl/wolfssl/sniffer_error.h \
    extern/wolfssl/wolfssl/ssl.h \
    extern/wolfssl/wolfssl/test.h \
    extern/wolfssl/wolfssl/version.h \
    extern/wolfssl/wolfssl/version.h.in \
    extern/wolfssl/wolfssl/wolfio.h \
    common/http/HttpResponseParser.h \
    lib/fiscal_register/chekonline/ChekOnlineResponseParser.h \
    common/evadts/EvadtsProtocol.h \
    common/utils/include/TestLed.h \
    lib/fiscal_manager/include/FiscalManager.h \
    common/sim900/test/TestGsmSignalQuality.h \
    common/fiscal_register/TestFiscalRegisterEventEngine.h \
    lib/fiscal_register/orange_data/OrangeDataProtocol.h \
    lib/sale_manager/mdb_slave/MdbSnifferCoinChanger.h \
    lib/sale_manager/mdb_slave/MdbSnifferCashless.h \
    lib/sale_manager/mdb_slave/SaleManagerMdbSlaveCore.h \
    lib/sale_manager/mdb_slave/MdbSnifferBillValidator.h \
    common/mdb/slave/com_gateway/MdbSlaveComGateway.h \
    lib/fiscal_register/nanokassa/NanokassaCommandLayer.h \
    lib/fiscal_register/nanokassa/NanokassaProtocol.h \
    lib/fiscal_register/ephor/EphorCommandLayer.h \
    lib/fiscal_register/ephor/EphorProtocol.h \
    lib/fiscal_register/ephor/EphorResponseParser.h \
    lib/fiscal_register/ephor/include/Ephor.h \
    common/config/include/ConfigModem.h \
    common/config/include/StatStorage.h \
    common/config/v3/Config3Modem.h \
    common/config/v4/Config4Modem.h \
    common/config/v4/event/Config4Event.h \
    common/config/v4/event/Config4EventList.h \
    common/config/v4/automat/Config4Automat.h \
    common/config/v4/automat/Config4AutomatData.h \
    common/config/v4/Config4ConfigIniter.h \
    common/config/v4/Config4ConfigParser.h \
    common/config/v1/boot/Config1Boot.h \
    common/config/v2/fiscal/Config2Cert.h \
    common/config/v2/fiscal/Config2Fiscal.h \
    common/config/v4/Config4AuditGenerator.h \
    common/config/v3/automat/Config3PriceIndex.h \
    common/config/v3/automat/Config3ProductIndex.h \
    common/config/v3/automat/Config3ProductIterator.h \
    common/config/v3/automat/Config3PriceList.h \
    common/config/v4/event/Config4EventIterator.h \
    common/config/v3/automat/Config3Automat.h \
    common/config/v3/event/Config3Event.h \
    common/config/v3/event/Config3EventData.h \
    common/config/v3/event/Config3EventIterator.h \
    common/config/v3/event/Config3EventList.h \
    common/config/v3/automat/Config3Device.h \
    common/config/v3/automat/Config3ProductList.h \
    common/config/v3/automat/Config3Product.h \
    common/config/v3/Config3ConfigIniter.h \
    common/config/v3/Config3ConfigParser.h \
    common/config/v3/Config3AuditGenerator.h \
    common/config/v4/automat/Config4DeviceList.h \
    common/config/v4/automat/Config4ProductIterator.h \
    common/config/v4/automat/Config4PaymentStat.h \
    common/config/v4/automat/Config4ProductList.h \
    common/config/v4/automat/Config4ProductListData.h \
    common/config/v4/automat/Config4ProductListStat.h \
    common/logger/RemoteLogger.h \
    lib/sale_manager/order/MdbSlaveSpire.h \
    lib/sale_manager/order/SaleManagerOrderCore.h \
    lib/sale_manager/mdb_no_cashless/SaleManagerMdbNoCashlessCore.h \
    common/mdb/slave/cashless/MdbSlaveCashless3.h \
    common/mdb/master/cashless/MdbMasterCashlessStack.h

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

DISTFILES += \
    extern/wolfssl/wolfssl/wolfcrypt/include.am \
    extern/wolfssl/wolfssl/include.am \
    extern/wolfssl/wolfssl/sniffer_error.rc
